pipeline {
    agent {
        label any
    }

    parameters {
        string(name: 'BUILD_NUMBER_TO_DELETE', defaultValue: '', description: 'Build number to delete deployment namespace')
    }

    environment {
        NAMESPACE = "developer_build-${params.BUILD_NUMBER_TO_DELETE}"
    }

    stages {
        stage('Validate input') {
            steps {
                script {
                    if (!params.BUILD_NUMBER_TO_DELETE?.trim()) {
                        error("BUILD_NUMBER_TO_DELETE is required!")
                    }
                }
            }
        }

        stage('Check namespace') {
            steps {
                script {
                    def nsExists = sh(script: "kubectl get namespace ${NAMESPACE} --no-headers || true", returnStdout: true).trim()
                    if (nsExists) {
                        echo "Namespace ${NAMESPACE} exists. Proceeding with deletion."
                    } else {
                        error "Namespace ${NAMESPACE} does not exist."
                    }
                }
            }
        }

        stage('Delete namespace') {
            steps {
                sh "kubectl delete namespace ${NAMESPACE}"
            }
        }
    }
}