pipeline {
    agent any

    parameters {
        string(name: 'BUILD_NUMBER_TO_DELETE', defaultValue: '', description: 'Build number to delete deployment namespace')
    }

    environment {
        NAMESPACE = "developer_build-${params.BUILD_NUMBER_TO_DELETE}"
    }

    stages {
        stage('Validate input') {
            steps {
                script {
                    if (!params.BUILD_NUMBER_TO_DELETE?.trim()) {
                        error("BUILD_NUMBER_TO_DELETE is required!")
                    }
                }
            }
        }

        stage('K8s Operations') {
            steps {
                withKubeConfig([credentialsId: 'k8s-kubeconfig-creds']) {
                    script {
                        sh 'kubectl cluster-info' // <- test kết nối ra console
                        def nsExists = sh(script: "kubectl get namespace ${NAMESPACE} --no-headers || true", returnStdout: true).trim()
                        
                        if (nsExists) {
                            echo "Namespace ${NAMESPACE} exists. Proceeding to delete..."
                            sh "kubectl delete namespace ${NAMESPACE}"
                        } else {
                            error "Namespace ${NAMESPACE} does not exist. Cannot delete."
                        }
                    }
                }
            }
        }
    }
}
